### PR TITLE
TS-17 Add SuperKey alias support

### PR DESCRIPTION
**Pull request by johnholt**
FileName_Info added a list of alias names for the super keys.

Filename modified to use alias names, a list of keys being built, and names by enumeration value.

Types added file name enumeration values.

Build Slice Action supports list of external co-managed files.

Layouts defined co-managed file information.

Signed-off-by: johnholt <john.d.holt@lexisnexisrisk.com>

### CODE REVIEW

**Comment by richardkchapman** [comment]
@johnholt Who can review this?

**Comment by johnholt** [comment]
Tony reviewed with no issues.  @ghalliday  should take a look at how I use NOTHOR(APPLY(... to see if this code is setting a good example or if the File Services actions should be re-worked.

**Comment by johnholt** [comment]
@richardkchapman  @ghalliday  This is good to go.  It is a simple initial version that supports a full replacement of the collection for each build.  A more complicated incremental update or even a slice scheme can be added later if desired.

**Comment by ghalliday** [comment]
@johnholt I think the file services calls are ok.  You might need to force the input dataset to a workunit global temporary though, otherwise if mfn is something more than an inline dataset the code will fail to generate.  E.g.

EXPORT Manage_Superkeys(FileName_Info info, DATASET(Managed_File_Names) mfn) := FUNCTION
  globalmfn := global(mfn, few);
  ac := SEQUENTIAL(
      // Make sure the aliases exist, create as necessary
      NOTHOR(APPLY(globalmfn,

**Pull request merged**
